version: '3.8'

services:
  # Django ilovasi konteyneri
  web:
    build: .
    container_name: oshxona_app
    restart: always
    expose:
      - "8000"  # Django serveri ichki tarmoqda ishlaydi
    volumes:
      - .:/app
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}  # .env faylidan o'qilgan
    env_file:
      - .env  # .env faylini konteynerga kiritish
    networks:
      - backend
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application  # Gunicorn bilan ishga tushirish

  # Nginx konteyneri (HTTPSni sozlash)
  nginx:
    image: nginx:latest
    container_name: oshxona_nginx
    restart: always
    ports:
      - "81:80"   # HTTP
      - "444:443" # HTTPS, boshqa dasturlarga halaqit bermaslik uchun 443 o‘rniga 444-portni foydalanamiz
    networks:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Nginx konfiguratsiya faylini konteynerga ko'chirish
      - ./certs:/etc/letsencrypt  # SSL sertifikatlari uchun papka
      - /var/www/certbot:/var/www/certbot  # Certbot uchun webroot
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web

  # Certbot konteyneri (SSL sertifikati olish va yangilash uchun)
  certbot:
    image: certbot/certbot
    container_name: oshxona_certbot
    volumes:
      - ./certs:/etc/letsencrypt  # SSL sertifikatlarini saqlash
      - /var/www/certbot:/var/www/certbot  # Webroot uchun papka
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - backend

networks:
  backend:
    driver: bridge
