version: '3.8'

services:
  # Django ilovasi konteyneri
  web:
    build: .
    container_name: oshxona_app
    restart: always
    expose:
      - "8000"  # Django serveri ichki tarmoqda ishlaydi
    volumes:
      - .:/app
    environment:
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}  # .env faylidan o'qilgan
    env_file:
      - .env  # .env faylini konteynerga kiritish

  # Nginx konteyneri (HTTPSni sozlash)
  nginx:
    image: nginx:latest
    container_name: oshxona_nginx
    restart: always
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Nginx konfiguratsiya faylini konteynerga ko'chirish
      - ./certs:/etc/letsencrypt  # SSL sertifikatlari uchun papka
    depends_on:
      - web

  # Certbot konteyneri (SSL sertifikati olish va yangilash uchun)
  certbot:
    image: certbot/certbot
    container_name: oshxona_certbot
    volumes:
      - ./certs:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  default:
    external:
      name: nginx_network  # Nginx va Django ilovasi o'rtasida tarmoqni bog'lash
