# Generated by Django 4.1.2 on 2022-11-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
