# Generated by Django 4.1.2 on 2022-11-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='profession',
            field=models.CharField(choices=[('cashier', 'kassir'), ('cook', 'oshpaz'), ('accountant', 'buxgalter')], default='cashier', max_length=32),
        ),
    ]
