# Generated by Django 4.1.3 on 2022-11-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeuser_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='profession',
            field=models.CharField(choices=[('cashier', 'kassir'), ('chef', 'oshpaz'), ('accountant', 'buxgalter')], default='cashier', max_length=32),
        ),
    ]
