# Generated by Django 4.1.3 on 2022-11-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_ref_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ref_code',
        ),
    ]
