# Generated by Django 4.1.3 on 2022-11-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_order_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
