# Generated by Django 4.1.3 on 2022-11-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order_cash_order_plastic_alter_order_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cash',
            field=models.IntegerField(),
        ),
    ]
