# Generated by Django 4.1.3 on 2022-11-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
