# Generated by Django 4.1.3 on 2022-11-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_order_completed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='user',
        ),
    ]
